version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: student-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: studentdb
    volumes:
      - mysql_data:/var/lib/mysql # This maps the internal DB folder to a persistent volume
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: student-api-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # This is the magic line
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword

volumes:
  mysql_data: # This tells Docker to manage a persistent storage area