spring.application.name=student-api

# If Docker is running, it uses the 'db' service name.
# If you run in IntelliJ normally, it will try localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/studentdb?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=30000